# -*- This python file uses the following encoding : coding:utf-8 -*-

import sys
import os

#  MAC OS SETUP
if sys.platform == "darwin":
    from setuptools import setup
    """
    This is an adaptation from a setup.py script generated by py2applet
    Usage:
        python setup.py py2app
    """

    APP = ['main.py']
    DATA_FILES = ['resources/Arlogo.icns']
    OPTIONS = {
        'iconfile': 'resources/ARsoftlogo.icns',
        'argv_emulation': True,
        'packages': ['sounddevice']
    }

    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )

# WINDOWS AND LINUX SETUP
else:
    from cx_Freeze import setup, Executable

    # PREPARING OPTIONS

    # Modules path
    path = sys.path

    # Icon path
    icone = "resources/ARsoftlogo.ico"

    # To able translations
    # includefiles = []
    # includefiles += [(r"resources", "resources")]

    # Options dictionnary
    options = {"path": path,
               # "include_files": includefiles,
               "compressed": False}

    # Include dll on windows
    if sys.platform == "win32":
        options["include_msvcr"] = True

    setup(name="AR Intercom",
          version="2.1",
          description="AR Intercom - Secured business chat application",
          author="Antares",
          author_email="antaresmugisho@gmail.com",
          executables=[Executable(script="main.py", target_name="AR Intercom", icon=icone)]
          )
# ===================================================== END ============================================================
