# Form implementation generated from reading ui file 'medias.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 411)
        MainWindow.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 40, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.arv_bubble = QtWidgets.QFrame(parent=self.centralwidget)
        self.arv_bubble.setGeometry(QtCore.QRect(20, 20, 301, 70))
        self.arv_bubble.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:10px;\n"
"\n"
"}")
        self.arv_bubble.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.arv_bubble.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.arv_bubble.setObjectName("arv_bubble")
        self.title = QtWidgets.QLabel(parent=self.arv_bubble)
        self.title.setGeometry(QtCore.QRect(52, 3, 241, 20))
        self.title.setStyleSheet("QLabel{\n"
"    background:#44FFFFFF;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.elapsed_time = QtWidgets.QLabel(parent=self.arv_bubble)
        self.elapsed_time.setGeometry(QtCore.QRect(52, 49, 51, 16))
        self.elapsed_time.setStyleSheet("QLabel{\n"
"    background:#22FFFFFF;\n"
"    border-radius:8px;\n"
"}")
        self.elapsed_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.elapsed_time.setObjectName("elapsed_time")
        self.total_time = QtWidgets.QLabel(parent=self.arv_bubble)
        self.total_time.setGeometry(QtCore.QRect(241, 49, 51, 16))
        self.total_time.setStyleSheet("QLabel{\n"
"    background:#22FFFFFF;\n"
"    border-radius:8px;\n"
"}")
        self.total_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_time.setObjectName("total_time")
        self.progress = QtWidgets.QProgressBar(parent=self.arv_bubble)
        self.progress.setGeometry(QtCore.QRect(52, 33, 241, 5))
        self.progress.setStyleSheet("QProgressBar{\n"
"        background-color:#AAC5C5C5;\n"
"        border-radius:2px;\n"
"        border:none;\n"
"        text-align:center;\n"
"}\n"
"\n"
"QProgressBar::chunk{    \n"
"       background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 52, 93, 255), stop:1 rgba(0, 121, 215, 255));\n"
"        border-radius:2px;\n"
"\n"
"}")
        self.progress.setMaximum(100)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(False)
        self.progress.setObjectName("progress")
        self.slider = QtWidgets.QSlider(parent=self.arv_bubble)
        self.slider.setGeometry(QtCore.QRect(52, 30, 241, 12))
        self.slider.setStyleSheet("QSlider{\n"
"    background:none;\n"
"}\n"
"\n"
"QSlider::groove{\n"
"    background:none;\n"
"    border:none;}\n"
"\n"
"QSlider::handle{\n"
"    height:12px;\n"
"    width:12px;\n"
"    background-color: rgb(0, 121, 215, 255);\n"
"    border-radius:6px;}\n"
"\n"
"QSlider::handle:hover{\n"
"    background-color: rgb(0, 52, 93, 255);}\n"
"\n"
"QSlider::handle:pressed{\n"
"    background-color: rgb(0, 121, 215, 255);}")
        self.slider.setMaximum(100)
        self.slider.setProperty("value", 0)
        self.slider.setSliderPosition(0)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.play_button = QtWidgets.QPushButton(parent=self.arv_bubble)
        self.play_button.setGeometry(QtCore.QRect(7, 16, 41, 41))
        self.play_button.setStyleSheet("QPushButton{\n"
"    background-image: url(:/cils/cils/cil-media-play.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position:center;\n"
"    border-radius:6px;\n"
"    border:none;\n"
"}")
        self.play_button.setObjectName("play_button")
        self.record_tip = QtWidgets.QFrame(parent=self.centralwidget)
        self.record_tip.setGeometry(QtCore.QRect(20, 110, 161, 31))
        self.record_tip.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:15px;\n"
"\n"
"}")
        self.record_tip.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.record_tip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.record_tip.setObjectName("record_tip")
        self.record_time = QtWidgets.QLabel(parent=self.record_tip)
        self.record_time.setGeometry(QtCore.QRect(45, 5, 71, 20))
        self.record_time.setStyleSheet("QLabel{\n"
"    background:#44FFFFFF;\n"
"    border-radius:none;\n"
"}")
        self.record_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.record_time.setObjectName("record_time")
        self.end_record = QtWidgets.QPushButton(parent=self.record_tip)
        self.end_record.setGeometry(QtCore.QRect(10, 5, 31, 20))
        self.end_record.setStyleSheet("QPushButton{\n"
"    image: url(:/cils/cils/cil-media-record-bl.png);\n"
"    background:#00FF00;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.end_record.setObjectName("end_record")
        self.cancel_record = QtWidgets.QPushButton(parent=self.record_tip)
        self.cancel_record.setGeometry(QtCore.QRect(119, 5, 31, 20))
        self.cancel_record.setStyleSheet("QPushButton{\n"
"    image: url(:/cils/cils/cil-media-stop-bl.png);\n"
"    background:#FF0000;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.cancel_record.setObjectName("cancel_record")
        self.arv_bubble_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.arv_bubble_2.setGeometry(QtCore.QRect(90, 220, 421, 101))
        self.arv_bubble_2.setStyleSheet("QFrame{\n"
"    background-color:#88FFFFFF;\n"
"    border-radius:10px;\n"
"\n"
"}")
        self.arv_bubble_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.arv_bubble_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.arv_bubble_2.setObjectName("arv_bubble_2")
        self.slider_2 = QtWidgets.QSlider(parent=self.arv_bubble_2)
        self.slider_2.setGeometry(QtCore.QRect(80, 30, 241, 12))
        self.slider_2.setStyleSheet("QSlider{\n"
"    background:none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal{\n"
"    background:none;\n"
"    height:4px;\n"
"    border:none;\n"
"    }\n"
"\n"
"QSlider::handle:horizontal{\n"
"    height:12px;\n"
"    width:12px;\n"
"    border-radius:6px;\n"
"    margin:-4px 10px -4px 10px;\n"
"    background-color: rgb(0, 121, 215, 255);}\n"
"    \n"
"QSlider::handle:hover{\n"
"    background-color: rgb(0, 52, 93, 255);}\n"
"\n"
"QSlider::handle:pressed{\n"
"    background-color: rgb(0, 121, 215, 255);}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"    background-color:grey;}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 52, 93, 255), stop:1 rgba(0, 121, 215, 255));}")
        self.slider_2.setMaximum(100)
        self.slider_2.setProperty("value", 0)
        self.slider_2.setSliderPosition(0)
        self.slider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_2.setObjectName("slider_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.slider.sliderMoved['int'].connect(self.progress.setValue) # type: ignore
        self.progress.valueChanged['int'].connect(self.slider.setValue) # type: ignore
        self.progress.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.title.setText(_translate("MainWindow", "ARV-20062021-1200"))
        self.elapsed_time.setText(_translate("MainWindow", "00:00"))
        self.total_time.setText(_translate("MainWindow", "00:00"))
        self.record_time.setText(_translate("MainWindow", "00:00"))
