# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(353, 336)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/AR logo/ARsoftlogo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SplashScreen.setWindowIcon(icon)
        SplashScreen.setStyleSheet("border:none;")
        self.base = QtWidgets.QFrame(parent=SplashScreen)
        self.base.setGeometry(QtCore.QRect(3, 3, 331, 301))
        self.base.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.base.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.base.setObjectName("base")
        self.gridLayout = QtWidgets.QGridLayout(self.base)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(parent=self.base)
        self.line.setMinimumSize(QtCore.QSize(265, 265))
        self.line.setMaximumSize(QtCore.QSize(265, 265))
        self.line.setStyleSheet("QFrame{\n"
"    border-radius:132px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setObjectName("line")
        self.circular_progress = QtWidgets.QFrame(parent=self.line)
        self.circular_progress.setGeometry(QtCore.QRect(0, 0, 265, 265))
        self.circular_progress.setMinimumSize(QtCore.QSize(160, 160))
        self.circular_progress.setMaximumSize(QtCore.QSize(265, 265))
        self.circular_progress.setStyleSheet("QFrame{\n"
"border-radius:132px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(250, 249, 251, 255), stop:\n"
"0.750 rgba(255, 0, 0, 255));\n"
"}")
        self.circular_progress.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_progress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_progress.setObjectName("circular_progress")
        self.background = QtWidgets.QFrame(parent=self.circular_progress)
        self.background.setGeometry(QtCore.QRect(7, 8, 251, 251))
        self.background.setMinimumSize(QtCore.QSize(251, 251))
        self.background.setMaximumSize(QtCore.QSize(251, 251))
        self.background.setStyleSheet("border-radius:125px;\n"
"border:46px solid rgb(0, 59, 89);\n"
"background; white;\n"
"border-color: rgb(79, 0, 0);")
        self.background.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.background.setObjectName("background")
        self.loading = QtWidgets.QLabel(parent=self.circular_progress)
        self.loading.setGeometry(QtCore.QRect(64, 220, 141, 21))
        self.loading.setMinimumSize(QtCore.QSize(141, 21))
        self.loading.setMaximumSize(QtCore.QSize(141, 21))
        self.loading.setStyleSheet("QLabel{    \n"
"    border-radius:5;\n"
"    color: rgba(255, 255, 255, 60);\n"
"    background:none;\n"
"    font-weight:0;\n"
"    font-family:Kirvy-Bold;\n"
"    font-size:12px;\n"
"}")
        self.loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading.setObjectName("loading")
        self.app_name = QtWidgets.QLabel(parent=self.circular_progress)
        self.app_name.setGeometry(QtCore.QRect(83, 26, 101, 21))
        self.app_name.setMinimumSize(QtCore.QSize(101, 21))
        self.app_name.setMaximumSize(QtCore.QSize(101, 21))
        self.app_name.setStyleSheet("QLabel{    \n"
"    border-radius:5;\n"
"    \n"
"    color:#bbFFFFFF;\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    font-family:Kirvy-Regular;\n"
"    font-weight:bold;\n"
"    font-size:12px;\n"
"}")
        self.app_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.app_name.setObjectName("app_name")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.circular_foreground = QtWidgets.QFrame(parent=SplashScreen)
        self.circular_foreground.setGeometry(QtCore.QRect(87, 72, 170, 170))
        self.circular_foreground.setMinimumSize(QtCore.QSize(170, 170))
        self.circular_foreground.setMaximumSize(QtCore.QSize(170, 170))
        self.circular_foreground.setStyleSheet("image: url(:/icons/icons/AR_logo.png);\n"
"border:none;")
        self.circular_foreground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.circular_foreground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circular_foreground.setObjectName("circular_foreground")

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "AR Intercom"))
        self.loading.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:400;\">Edited by Antares</span></p></body></html>"))
        self.app_name.setText(_translate("SplashScreen", "AR Intercom 2"))
